### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by TheBaconSpace** [svinkle/twitch-tv-widget#1]
Can you make this Available for http://beam.pro http://developer.beam.pro is The api

**Comment by TheBaconSpace** [comment]
Would love it @svinkle

**Comment by svinkle** [comment]
@TheBaconSpace, this widget turned in to http://streambadge.com. You could ask there but I doubt it will ever happen. Seems like it is no longer maintained after I sold it to someone else.

**Comment by TheBaconSpace** [comment]
Are You Able to do it as a Side project?
